### ISSUE TITLE
[HelpNeeded] java.lang.UnsatisfiedLinkError: no lwjgl in java.library.path

### ISSUE THREAD

**Issue by SrTobi** [mvallerie/sbt-scage-plugin#4]
Hi,

I had some problems setting up scage with SBT and tried your example.
It seems to work but I get the following error when I want to start the example:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no lwjgl in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
    at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    at java.lang.System.loadLibrary(System.java:1122)
    at org.lwjgl.Sys$1.run(Sys.java:73)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
    at org.lwjgl.Sys.loadLibrary(Sys.java:95)
    at org.lwjgl.Sys.<clinit>(Sys.java:112)
    at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
    at com.github.dunnololda.scage.handlers.RendererLib$class.initgl(Renderer.scala:433)
    at com.github.dunnololda.scage.handlers.RendererLib$.initgl(Renderer.scala:515)
    at com.github.dunnololda.scage.ScreenApp.main(ScageScreen.scala:60)
    at HelloWorldExample.main(HelloWorldExample.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

The problem seems to be, that I am missing some native library files. But before I try to copy them manually, I wanted to ask if there is a automatic way, so I do not have to repeat the manual process on every machine I want to develop.

By the way: I use Intellij with SBT. maybe there is the problem?

**Comment by mvallerie** [comment]
Hey !

> The problem seems to be, that I am missing some native library files. But before I try to copy them manually, I wanted to ask if there is a automatic way, so I do not have to repeat the manual process on every machine I want to develop.

Actually the plugin should download + extract those lwjgl native deps for you. After running `sbt run` from `example` folder, here is what you should get (anything similar, depending on your OS, should be fine) in `example/libs` : 

``` libs/natives/liblwjgl.so
libs/natives/META-INF/MANIFEST.MF
libs/natives/liblwjgl64.so
libs/natives/libopenal.so
libs/natives/libopenal64.so
```

Do you have those on your side ? Also, may you submit your sbt log ? You should have this line in there : 

`[info] Extracting LWJGL natives to ./libs/natives`

Thanks in adv.

**Comment by SrTobi** [comment]
Thanks! It worked like a charm. First I tried to run `sbt run` in a terminal (I use windows), but it only said `bash: sbt: command not found` :smile:.

I found out that I had to add a `SBT Task` in Intellij like this:

![sbt-task](https://cloud.githubusercontent.com/assets/4148534/14202053/1c76255e-f7f6-11e5-8f0b-f1c6dea26d73.PNG)

And it worked perfectly. Thank you

**Comment by mvallerie** [comment]
Glad you figured it out :). I'm closing this.
